name: Production workflow
on:
  push:
    branches:
      - main
      
jobs:
  checks:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build
      - run: cargo test
      
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: checks
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_SSH_KEY }}
          script: |
            echo "Successfully connected"
            cd Documents/GitHub/tjm-backend
            git pull
            docker compose down --rmi all
            docker compose pull
            docker compose up -d
